version: '3'

services:

  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: cpatriota/nodeexpress
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    tty: true
    networks:
      - node-network
    ports:
      - "3000:3000" 
    volumes: 
      - ./node:/usr/src/app
    depends_on: 
       - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    build: 
        context: ./
        dockerfile: DockerfileNginx
    image: cpatriota/nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - app
    depends_on:
      - app
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge